# Generated by Django 5.1 on 2025-10-20 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HunterIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('ip_hash', models.CharField(max_length=64, unique=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                            related_name='reported_ips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
