# Generated by Django 5.1 on 2025-10-21 00:23
"""Configuring the migration for Django."""
from django.db import migrations, models


class Migration(migrations.Migration):
    """Class for Migration."""
    dependencies = [
        ('users', '0002_hunter_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('password_hash', models.CharField(max_length=128)),
            ],
        ),
    ]
