# Generated by Django 4.2.25 on 2025-11-01 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_force_password_change_userloginip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='government',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_ips', to=settings.AUTH_USER_MODEL),
        ),
    ]
