# Generated by Django 4.2.25 on 2025-11-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_government_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('simple', 'Simple'), ('silver', 'Silver'), ('gold', 'Gold'), ('architect', 'Architect'), ('inquisition', 'Inquisition')], default='simple', max_length=15),
        ),
    ]
