# Generated by Django 4.2.25 on 2025-11-02 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('promotion', 'Promotion'), ('excommunication', 'Excommunication')], max_length=20)),
                ('roles_allowed_vote', models.JSONField(default=list)),
                ('promotion_role', models.CharField(blank=True, choices=[('simple', 'Simple'), ('silver', 'Silver'), ('gold', 'Gold'), ('architect', 'Architect'), ('inquisition', 'Inquisition')], max_length=20, null=True)),
                ('for_amount', models.IntegerField(default=0)),
                ('against_amount', models.IntegerField(default=0)),
                ('progress', models.FloatField(default=0.0)),
                ('nominated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominated_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_for', models.BooleanField(default=False)),
                ('is_against', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_logs', to=settings.AUTH_USER_MODEL)),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_logs', to='moderation.vote')),
            ],
        ),
    ]
