# Generated by Django 5.1 on 2025-10-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigfootpost',
            name='image',
            field=models.ImageField(upload_to='photo_storage/'),
        ),
        migrations.AlterField(
            model_name='ghostpost',
            name='image',
            field=models.ImageField(upload_to='photo_storage/'),
        ),
        migrations.AlterField(
            model_name='otherpost',
            name='image',
            field=models.ImageField(upload_to='photo_storage/'),
        ),
        migrations.AlterField(
            model_name='ufopost',
            name='image',
            field=models.ImageField(upload_to='photo_storage/'),
        ),
    ]
