# Generated by Django 4.2.25 on 2025-11-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_bigfootpost_lat_bigfootpost_lng_ghostpost_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigfootpost',
            name='image',
            field=models.ImageField(upload_to='./'),
        ),
        migrations.AlterField(
            model_name='ghostpost',
            name='image',
            field=models.ImageField(upload_to='./'),
        ),
        migrations.AlterField(
            model_name='otherpost',
            name='image',
            field=models.ImageField(upload_to='./'),
        ),
        migrations.AlterField(
            model_name='ufopost',
            name='image',
            field=models.ImageField(upload_to='./'),
        ),
    ]
